# Generated by Django 6.0.5 on 2026-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'admin'), ('encargad@', 'encargad@'), ('cliente', 'cliente')], max_length=50),
        ),
    ]
