# Generated by Django 6.0.5 on 2026-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
