# Generated by Django 6.0.5 on 2026-05-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanasMarketing',
            fields=[
                ('id_campania', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=50)),
            ],
            options={
                'verbose_name': 'Campaña de Marketing',
                'verbose_name_plural': 'Campañas de Marketing',
                'db_table': 'campañas_marketing',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ComposicionProducto',
            fields=[
                ('id_composicion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Composición de Producto',
                'verbose_name_plural': 'Composiciones de Productos',
                'db_table': 'composicion_producto',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='EntregasLogistica',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('estado_entrega', models.CharField(choices=[('Asignado', 'Asignado'), ('En Ruta', 'En Ruta'), ('Entregado', 'Entregado'), ('Fallido', 'Fallido')], default='Asignado', max_length=50)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('foto_evidencia_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Entrega Logística',
                'verbose_name_plural': 'Entregas Logísticas',
                'db_table': 'entregas_logistica',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('direccion_entrega', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('Listo', 'Listo'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50)),
                ('total_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota_entrega', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='TransaccionesFinancieras',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('QR', 'QR'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Billetera Móvil', 'Billetera Móvil')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'db_table': 'transacciones_financieras',
            },
        ),
        migrations.CreateModel(
            name='TransaccionesPuntos',
            fields=[
                ('id_transaccion_puntos', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Ganancia', 'Ganancia'), ('Canje', 'Canje')], max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'verbose_name_plural': 'Transacciones de Puntos',
                'db_table': 'transacciones_puntos',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('Monto Fijo', 'Monto Fijo')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_requeridos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Usado', 'Usado'), ('Expirado', 'Expirado')], default='Activo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('id_campania', models.ForeignKey(blank=True, db_column='id_campania', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.campanasmarketing')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupones',
            },
        ),
    ]
