# Generated by Django 6.0.5 on 2026-05-12 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('preferencias', models.TextField(blank=True, help_text='Ej: Prefiere rosas rojas, alergias, etc.', null=True)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Compra de cintas, bases sin proveedor fijo', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_recibo', models.ImageField(blank=True, null=True, upload_to='recibos/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Arreglo de peluche con chocolates', max_length=200)),
                ('precio_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_materiales_estimado', models.DecimalField(decimal_places=2, help_text='Para calcular la ganancia real', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adelanto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En Preparación'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('foto_comprobante_entrega', models.ImageField(blank=True, help_text='Obligatorio para marcar como entregado', null=True, upload_to='entregas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='operaciones.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.producto')),
            ],
        ),
    ]
