# Generated by Django 6.0.5 on 2026-05-16 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='entregaslogistica',
            name='id_delivery',
            field=models.ForeignKey(blank=True, db_column='id_delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='composicionproducto',
            name='id_material',
            field=models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.CASCADE, to='operaciones.material'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cupon_aplicado',
            field=models.ForeignKey(blank=True, db_column='id_cupon_aplicado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.cupon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario_asignado',
            field=models.ForeignKey(blank=True, db_column='id_usuario_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaslogistica',
            name='id_pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='operaciones.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='operaciones.pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.categoria'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='operaciones.producto'),
        ),
        migrations.AddField(
            model_name='composicionproducto',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='operaciones.producto'),
        ),
        migrations.AddField(
            model_name='material',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.proveedor'),
        ),
        migrations.AddField(
            model_name='transaccionesfinancieras',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='transaccionesfinancieras',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.pedido'),
        ),
        migrations.AddField(
            model_name='transaccionespuntos',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='transaccionespuntos',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.pedido'),
        ),
    ]
