# Generated by Django 6.0.5 on 2026-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_producto_codigo_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock disponible del producto'),
        ),
    ]
